name: Sync posts to main site

on:
  push:
    - "_posts/**"
  branches:
    - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (from-here)
        uses: actions/checkout@v4

      - name: Configure Git
        uses: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"

      - name: Clone target repo (push-here)
        uses: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/mirgis/push-here.git target-repo

      - name: Copy new posts
        run: |
          cp -ruv _posts/. target-repo/_posts/

      - name: Commit and push
        run: |
          cd target-repo
          git add _posts/
          git commit -m "Sync posts from from-here" || "No changes to commit!"
          git push
